### ISSUE TITLE
method `session_new_cb' called on hidden T_DATA object (NotImplementedError)

### ISSUE THREAD

**Issue by casperisfine** [ruby/openssl#464] opened 2021-10-13 15:02 UTC
A weird error that happened once in production.

Ruby `3.0.2 (linux)`

Full backtrace:

```
/usr/local/ruby/lib/ruby/3.0.0/openssl/buffering.rb:205:in `sysread_nonblock': hidden object cannot have instance variables (TypeError)
    from /usr/local/ruby/lib/ruby/3.0.0/openssl/buffering.rb:205:in `read_nonblock'
    from gems/net-protocol-0.1.1/lib/net/protocol.rb:212:in `rbuf_fill'
    from gems/net-protocol-0.1.1/lib/net/protocol.rb:193:in `readuntil'
    from gems/net-protocol-0.1.1/lib/net/protocol.rb:203:in `readline'
    from /usr/local/ruby/lib/ruby/3.0.0/net/http/response.rb:42:in `read_status_line'
    from /usr/local/ruby/lib/ruby/3.0.0/net/http/response.rb:31:in `read_new'
    from /usr/local/ruby/lib/ruby/3.0.0/net/http.rb:1557:in `block in transport_request'
    from /usr/local/ruby/lib/ruby/3.0.0/net/http.rb:1548:in `catch'
    from /usr/local/ruby/lib/ruby/3.0.0/net/http.rb:1548:in `transport_request'
...

Caused by: /usr/local/ruby/lib/ruby/3.0.0/openssl/buffering.rb:205:in `sysread_nonblock': method `session_new_cb' called on hidden T_DATA object (0x00007f17df28b0d8 flags=0xc) (NotImplementedError)
    from /usr/local/ruby/lib/ruby/3.0.0/openssl/buffering.rb:205:in `read_nonblock'
    from gems/net-protocol-0.1.1/lib/net/protocol.rb:212:in `rbuf_fill'
    from gems/net-protocol-0.1.1/lib/net/protocol.rb:193:in `readuntil'
    from gems/net-protocol-0.1.1/lib/net/protocol.rb:203:in `readline'
    from /usr/local/ruby/lib/ruby/3.0.0/net/http/response.rb:42:in `read_status_line'
    from /usr/local/ruby/lib/ruby/3.0.0/net/http/response.rb:31:in `read_new'
    from /usr/local/ruby/lib/ruby/3.0.0/net/http.rb:1557:in `block in transport_request'
    from /usr/local/ruby/lib/ruby/3.0.0/net/http.rb:1548:in `catch'
    from /usr/local/ruby/lib/ruby/3.0.0/net/http.rb:1548:in `transport_request'
...
```

We do call `GC.compact` once, so maybe there's a static VALUE reference that isn't properly declared to the GC?

**Comment by rhenium** [comment] 2021-10-14 06:46
This causes segfault, so this indeed seems to be the root cause.

```ruby
require "socket"
require "openssl"

p1, p2 = UNIXSocket.pair
ctx = OpenSSL::SSL::SSLContext.new.tap { |x| x.security_level = 0; x.ciphers = "aNULL" }
s1 = OpenSSL::SSL::SSLSocket.new(p1, ctx)
s2 = OpenSSL::SSL::SSLSocket.new(p2, ctx)
GC.verify_compaction_references
[
  Thread.new { s1.accept },
  Thread.new { s2.connect },
].map(&:join)
```

**Comment by casperisfine** [comment] 2021-10-14 06:56
Yes, @XrXr came to the same conclusion: https://github.com/XrXr/openssl/commit/ad02bb94b9a8e3718608c019c14a191df0329a72

**Comment by rhenium** [comment] 2021-10-14 07:11
https://github.com/ruby/openssl/pull/465 should fix this by adding `rb_gc_mark()` calls.

**Comment by rhenium** [comment] 2021-10-16 08:44
openssl 2.1.3 and 2.2.1 have been released with the fix. Thanks for reporting this issue!

**Closed by rhenium** 2021-10-16 08:44 UTC
