### ISSUE TITLE
truffleruby-head 24.0.0-dev: Failing to compile dependant stringio gem.

### ISSUE THREAD

**Issue by junaruga** [ruby/openssl#699] opened 2023-11-23 22:48 UTC
I see the following build errors in the truffleruby-head cases in CI.

https://github.com/ruby/openssl/actions/runs/6974797041/job/18981006346#step:3:20

```
  /home/runner/.rubies/truffleruby-head/bin/ruby --version
  truffleruby 24.0.0-dev-9a84a125, like ruby 3.2.2, GraalVM CE Native [x86_64-linux]
```

https://github.com/ruby/openssl/actions/runs/6974797041/job/18981006346#step:4:20

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/home/runner/.rubies/truffleruby-head/lib/gems/gems/stringio-3.0.9/ext/stringio
/home/runner/.rubies/truffleruby-head/bin/ruby extconf.rb
creating Makefile

current directory:
/home/runner/.rubies/truffleruby-head/lib/gems/gems/stringio-3.0.9/ext/stringio
make DESTDIR\= sitearchdir\=./.gem.20231123-1869-nljcsp
sitelibdir\=./.gem.20231123-1869-nljcsp clean

current directory:
/home/runner/.rubies/truffleruby-head/lib/gems/gems/stringio-3.0.9/ext/stringio
make DESTDIR\= sitearchdir\=./.gem.20231123-1869-nljcsp
sitelibdir\=./.gem.20231123-1869-nljcsp
compiling stringio.c
stringio.c: In function ‘readable’:
stringio.c:138:7: error: implicit declaration of function ‘RBASIC’
[-Werror=implicit-function-declaration]
  138 |     ((RBASIC(strio)->flags & STRIO_##mode) && \
      |       ^~~~~~
...
```

In the past CI result where the truffleruby-head pass, the truffleruby version was 23.1.1. So, I guess the the new version `24.0.0-dev` triggered the error.
https://github.com/ruby/openssl/actions/runs/6894870154/job/18757626125#step:3:19

```
   /home/runner/.rubies/truffleruby-23.1.1/bin/ruby --version
  truffleruby 23.1.1, like ruby 3.2.2, Oracle GraalVM Native [x86_64-linux]
```

In both passed and failing cases, the stringio gem version 3.0.9 are used. So, I don't think the stringio triggered the issue.

**Comment by junaruga** [comment] 2023-11-23 22:49
@eregon Do you have any idea about how to fix the issue? Thanks.

**Comment by eregon** [comment] 2023-11-24 11:55
Thanks for the ping.
It's due to https://github.com/oracle/truffleruby/issues/3118. It's expected that `RBASIC(obj)->flags` is no longer supported, because basically it cannot be.
I'll take a look at fixing https://github.com/ruby/stringio.

**Comment by eregon** [comment] 2023-11-24 12:01
BTW it seems a bit weird that ruby/openssl depends on the stringio gem.
Looking at Gemfile.lock it's because the openssl Gemfile depends on `rdoc->psych->stringio`.
Ideally it'd just use the stdlib stringio and not install the stringio gem.

**Comment by eregon** [comment] 2023-11-24 12:27
https://github.com/ruby/stringio/pull/71

**Comment by junaruga** [comment] 2023-11-24 13:49
> BTW it seems a bit weird that ruby/openssl depends on the stringio gem. Looking at Gemfile.lock it's because the openssl Gemfile depends on `rdoc->psych->stringio`. Ideally it'd just use the stdlib stringio and not install the stringio gem.

Thanks for your work!

For the rdoc dependency in the `Gemfile`, https://github.com/ruby/openssl/commit/4312b072fb02d5f16074493757caa3824eca64a5 is the reason. In Fedora Linux and the downstream Linux distro Ruby RPM packages, the rdoc is not default gem of the Ruby.

**Comment by eregon** [comment] 2023-11-24 14:53
Do you know why openssl needs rdoc at all? I would think running openssl tests doesn't need it.

**Comment by junaruga** [comment] 2023-11-24 21:02
> Do you know why openssl needs rdoc at all? I would think running openssl tests doesn't need it.

Yes, because the `Rakeflie` has a task to create the openssl gem's rdoc document. Perhaps you like to create the new `test` group in `Rakefile`, then only install the gem packages in the `test` group excluding the `rdoc` in the `development` group in the CI?

https://github.com/ruby/openssl/blob/27237de417f386b8133fdf092af450b956a9a08e/Rakefile#L37-L40

**Comment by junaruga** [comment] 2023-11-25 07:37
I sent the PR https://github.com/ruby/openssl/pull/701 to pass CI avoiding this issue.

**Comment by junaruga** [comment] 2023-11-28 02:00
As stringio version 3.1.0 including the https://github.com/ruby/stringio/pull/71, I ran the GitHub Actions on my forked repository for the latest master branch. Right now stringio version 3.0.9 is downloaded in the CI. GitHub has a cache for that? Maybe we need to wait.
 
https://github.com/junaruga/ruby-openssl/actions/runs/7013145579/job/19078824139#step:4:15

**Comment by eregon** [comment] 2023-11-28 10:41
I can reproduce it locally, also on CRuby.
It sounds like a rubygems.org cache or bug.
If I add `gem "stringio", "3.1.0"` in openssl Gemfile I get (on CRuby 3.2):
```
$ bundle lock
Fetching gem metadata from https://rubygems.org/........
Could not find gem 'stringio (= 3.1.0)' in rubygems repository https://rubygems.org/ or installed locally.

The source contains the following gems matching 'stringio':
  * stringio-0.0.1
  * stringio-0.0.2
  * stringio-0.1.0
  * stringio-0.1.3
  * stringio-0.1.4
  * stringio-3.0.0
  * stringio-3.0.1
  * stringio-3.0.2.pre1-java
  * stringio-3.0.2.pre1
  * stringio-3.0.2-java
  * stringio-3.0.2
  * stringio-3.0.3-java
  * stringio-3.0.3
  * stringio-3.0.4-java
  * stringio-3.0.4
  * stringio-3.0.5-java
  * stringio-3.0.5
  * stringio-3.0.6-java
  * stringio-3.0.6
  * stringio-3.0.7-java
  * stringio-3.0.7
  * stringio-3.0.8-java
  * stringio-3.0.8
  * stringio-3.0.9-java
  * stringio-3.0.9
```

**Comment by eregon** [comment] 2023-11-28 10:42
Also:
```
$ gem info -r stringio

*** REMOTE GEMS ***

stringio (3.1.0)
    Platform: java, ruby
    Authors: Nobu Nakada, Charles Oliver Nutter
    Homepage: https://github.com/ruby/stringio

    Pseudo IO on String

$ gem install stringio
Building native extensions. This could take a while...
Successfully installed stringio-3.0.9
1 gem installed
```

**Comment by eregon** [comment] 2023-11-28 10:47
I filed https://github.com/rubygems/rubygems/issues/7202

**Comment by eregon** [comment] 2023-11-28 13:09
The rubygems.org issue is fixed now.
So I think we can close this as well as #701 and #704.

**Closed** 2023-12-03 01:26 UTC
