### ISSUE TITLE
warning: no such builtin loader for `cloudhsm'

### ISSUE THREAD

**Issue by kyleoliveira** [ruby/openssl#189] opened 2018-02-22 23:44 UTC
I'm trying to use [AWS CloudHSM's OpenSSL library](https://docs.aws.amazon.com/cloudhsm/latest/userguide/openssl-library-install.html) with the `openssl` gem. When I do this:
```ruby
private_key = OpenSSL::Engine.by_id("cloudhsm").load_private_key("CKA_LABEL=#{key_label}")
```
I get this error:
```
test.rb:19: warning: no such builtin loader for `cloudhsm'
	SDK Version: 2.03
test.rb:19:in `load_private_key': no load function (OpenSSL::Engine::EngineError)
	from test.rb:19:in `<main>'
```

I have followed the steps in the AWS documentation I linked above and I am able to load the engine via the `openssl` program itself without errors.

My best guess is that because `cloudhsm` isn't listed in the if-statements [here](https://github.com/ruby/openssl/blob/5c5bf71394b286698956438a3694b71640d6895b/ext/openssl/ossl_engine.c#L94), I'm getting that message, but I'm not 100% sure on this.

Did I miss something, or would there need to be an update to add support for this?

**Comment by kyleoliveira** [comment] 2018-02-23 22:49
Additionally, I've tried using the `dynamic` engine to load the `cloudhsm` library like so:
```ruby
OpenSSL::Engine.load
puts OpenSSL::Engine.engines.map(&:inspect)

e = OpenSSL::Engine.engines[1]
e.ctrl_cmd("SO_PATH", "/opt/cloudhsm/lib/libcloudhsm_openssl.so")
e.ctrl_cmd("ID", "cloudhsm")
e.ctrl_cmd("LOAD")
puts e.inspect
puts e.cmds.inspect

private_key = e.load_private_key("CKA_LABEL=#{key_label}")
```
I'm still getting errors, but different ones:
```
#<OpenSSL::Engine id="rdrand" name="Intel RDRAND engine">
#<OpenSSL::Engine id="dynamic" name="Dynamic engine loading support">
#<OpenSSL::Engine id="cloudhsm" name="CloudHSM hardware engine support">
[]
test.rb:27:in `load_private_key': not initialised (OpenSSL::Engine::EngineError)
	from test.rb:27:in `<main>'
```
If I try selecting that engine by ID it fails with the error in my original posting.

This feels like it's closer to working, but it still doesn't seem to be correct.

**Comment by bidigo** [comment] 2018-04-20 10:53
I had a similar problem (only with YubiHSM) and got it working by using `OpenSSL::Engine.by_id` method to get access to the engine after it has been loaded:

```ruby
...
e = OpenSSL::Engine.by_id('cloudhsm')
private_key = e.load_private_key("CKA_LABEL=#{key_label}")
```

The reason it seems to work is that the `by_id` method is the only place where the OpenSSL `ENGINE_Init()` function is called. Without calling `by_id` the engine will never be initialized.

**Comment by Fornacula** [comment] 2019-08-19 16:09
Giving me some bigger headaches too for longer time now already.

```ruby
irb(main):001:0> OpenSSL::Engine.load
=> true
irb(main):002:0> e = OpenSSL::Engine.by_id('cloudhsm')
	SDK Version: 2.03
=> #<OpenSSL::Engine id="cloudhsm" name="CloudHSM hardware engine support">
irb(main):003:0> cert_file = File.read "ruby_hsm.crt"
=> "-----BEGIN CERTIFICATE-----\n.........
irb(main):004:0> key_file = File.read "ruby_hsm_fake_private.key"
=> "-----BEGIN RSA PRIVATE KEY-----\n..........
irb(main):005:0> ssl_options = {
irb(main):006:1*     verify: false,
irb(main):007:1*     ca_path: '/etc/ssl/certs',
irb(main):008:1*     ca_file: 'ca-bundle.crt',
irb(main):009:1*     client_cert: OpenSSL::X509::Certificate.new(cert_file),
irb(main):010:1*     client_key: OpenSSL::PKey::RSA.new(key_file)
irb(main):011:1>   }
=> {:verify=>false, :ca_path=>"/etc/ssl/certs", :ca_file=>"ca-bundle.crt", :client_cert=>#<OpenSSL::X509::Certificate: subject=#<OpenSSL::X509::Name:0x00000001e48648>, issuer=#<OpenSSL::X509::Name:0x00000001e48670>, serial=#<OpenSSL::BN:0x00000001e48698>, not_before=.............
irb(main):012:0> dest = "https://127.0.0.1"
=> "https://127.0.0.1"
irb(main):013:0> c = Faraday::Connection.new(dest, ssl: ssl_options)
=> #<Faraday::Connection:0x00000001e71458 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.15.4"}, @params={}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions ca_file="ca-bundle.crt", ca_path="/etc/ssl/certs", client_cert=#<OpenSSL::X509::Certificate: subject=#<OpenSSL::X509::Name:0x00000001bf3b18>, issuer=#<OpenSSL::X509::Name:0x00000001bf3b40>, serial=#<OpenSSL::BN:0x00000001bf3b68>, not_before=..........
irb(main):014:0> c.get
Faraday::SSLError: SSL_connect returned=1 errno=0 state=error: EVP lib
	from /usr/share/ruby/net/http.rb:921:in `connect'
	from /usr/share/ruby/net/http.rb:921:in `block in connect'
	from /usr/share/ruby/timeout.rb:52:in `timeout'
	from /usr/share/ruby/net/http.rb:921:in `connect'
	from /usr/share/ruby/net/http.rb:862:in `do_start'
	from /usr/share/ruby/net/http.rb:851:in `start'
	from /usr/share/ruby/net/http.rb:1373:in `request'
	from /usr/share/ruby/net/http.rb:1131:in `get'
	from /usr/local/share/gems/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:85:in `perform_request'
	from /usr/local/share/gems/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:43:in `block in call'
	from /usr/local/share/gems/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
	from /usr/local/share/gems/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:38:in `call'
	from /usr/local/share/gems/gems/faraday-0.15.4/lib/faraday/request/url_encoded.rb:15:in `call'
	from /usr/local/share/gems/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	from /usr/local/share/gems/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	from /usr/local/share/gems/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'
	from (irb):15
	from /usr/bin/irb:12:in `<main>'irb(main):016:0>
```

Also, by trying to apply @kyleoliveira 's example I get stuck already on first `ctrl_cmd` line:

```ruby
irb(main):001:0> OpenSSL::Engine.load
=> true
irb(main):002:0> e = OpenSSL::Engine.by_id('cloudhsm')
	SDK Version: 2.03
=> #<OpenSSL::Engine id="cloudhsm" name="CloudHSM hardware engine support">
irb(main):003:0> e.ctrl_cmd("SO_PATH", "/opt/cloudhsm/lib/libcloudhsm_openssl.so")
OpenSSL::Engine::EngineError: invalid cmd name
	from (irb):3:in `ctrl_cmd'
	from (irb):3
	from /usr/bin/irb:12:in `<main>'
```

Checked the methods related to engine and found `:cmds` from there which gives me empty array:
```ruby
irb(main):004:0> e.methods
=> [:id, :name, :finish, :cipher, :digest, :load_private_key, :load_public_key, :set_default, :ctrl_cmd, :cmds, :inspect, :nil?, :===, :=~, :!~, :eql?, :hash, :<=>, :class, :singleton_class, :clone, :dup, :taint, :tainted?, :untaint, :untrust, :untrusted?, :trust, :freeze, :frozen?, :to_s, :methods, :singleton_methods, :protected_methods, :private_methods, :public_methods, :instance_variables, :instance_variable_get, :instance_variable_set, :instance_variable_defined?, :remove_instance_variable, :instance_of?, :kind_of?, :is_a?, :tap, :send, :public_send, :respond_to?, :extend, :display, :method, :public_method, :define_singleton_method, :object_id, :to_enum, :enum_for, :==, :equal?, :!, :!=, :instance_eval, :instance_exec, :__send__, :__id__]
irb(main):005:0> e.cmds
=> []
```

Tried to see if any other engines give other outputs for cmds which only made me more confused (why _rdrand_ works while _dynamin_ can't even by found by `.by_id` method):
```ruby
irb(main):020:0> puts OpenSSL::Engine.engines.map(&:inspect)
#<OpenSSL::Engine id="rdrand" name="Intel RDRAND engine">
#<OpenSSL::Engine id="dynamic" name="Dynamic engine loading support">
#<OpenSSL::Engine id="cloudhsm" name="CloudHSM hardware engine support">
irb(main):021:0> er = OpenSSL::Engine.by_id('rdrand')
=> #<OpenSSL::Engine id="rdrand" name="Intel RDRAND engine">
irb(main):022:0> er.cmds
=> []
irb(main):023:0> ed = OpenSSL::Engine.by_id('dynamic')
OpenSSL::Engine::EngineError:
	from (irb):23:in `by_id'
	from (irb):23
	from /usr/bin/irb:12:in `<main>'
```

Thought I'd try to load the private key but this also doesn't seem to work:
```ruby
irb(main):006:0> key_label = 'nginx-selfsigned-fake_PEM.key'
=> "nginx-selfsigned-fake_PEM.key"
irb(main):007:0> private_key = e.load_private_key("CKA_LABEL=#{ key_label }")
OpenSSL::Engine::EngineError: no load function
	from (irb):7:in `load_private_key'
	from (irb):7
	from /usr/bin/irb:12:in `<main>'
```

Trying to search why there's no load function I found this line: https://github.com/ruby/openssl/blob/master/ext/openssl/ossl_engine.c#L364 which ends with (`engine.load_private_key(id = nil, data = nil) -> OpenSSL::PKey`) so I assumed it needs OpenSSL::Pkey object:

```ruby
irb(main):009:0> key = OpenSSL::PKey::RSA.new(File.read('ruby_hsm_fake_private.key'))
=> #<OpenSSL::PKey::RSA:0x00000002033db8>
```

...which wasn't successful also:
```ruby
irb(main):010:0> e.load_private_key(key)
TypeError: no implicit conversion of OpenSSL::PKey::RSA into String
	from (irb):10:in `load_private_key'
	from (irb):10
	from /usr/bin/irb:12:in `<main>'
```
Though I'd give it a more _pem_ look but still no luck :D
```ruby
irb(main):014:0> e.load_private_key(key.to_pem)
OpenSSL::Engine::EngineError: no load function
	from (irb):14:in `load_private_key'
	from (irb):14
	from /usr/bin/irb:12:in `<main>'
```

This has been a huge blocker so far, really stuck with it and running out of ideas.

**Comment by ioquatix** [comment] 2019-10-31 21:57
There is a PR for this, but I'm going to need someone to take the lead on rebasing and testing:

https://github.com/ruby/openssl/pull/190

If can be done this month it will land in Ruby 2.7

**Comment by ggeligible** [comment] 2020-02-21 00:31
@kyleoliveira @Fornacula  does load_private_key work after the change? I am still facing the same issue with the master. I used `rake compile` followed by `gem build openssl` to build the extension and Gem.

I have cloudhsm-client running and using the code below:
```
gem "openssl"
require "openssl"

OpenSSL::Engine.load
engine = OpenSSL::Engine.by_id("cloudhsm")
label = "CKA_LABEL=label"
>> engine.load_private_key(label)
OpenSSL::Engine::EngineError: no load function
	from (irb):13:in `load_private_key'
	from (irb):13
```
Let me know if I am missing anything as same code works well with the older version of hsm engine (Cloudhsm classic/v1).

**Comment by rhenium** [comment] 2020-02-21 09:31
> ```
> >> engine.load_private_key(label)
> OpenSSL::Engine::EngineError: no load function
> 	from (irb):13:in `load_private_key'
> 	from (irb):13
> ```

My grep in OpenSSL source suggests the error message means that the cloudhsm engine does not implement the `load_privkey` function in it.

Since the document of CloudHSM (https://docs.aws.amazon.com/cloudhsm/latest/userguide/ssl-offload-import-or-generate-private-key-and-certificate.html) doesn't include any instructions that would use ENGINE_load_private_key(3) (which is what OpenSSL::Engine#load_private_key calls internally), I suspect it is by design.

The documents suggest using `-engine cloudhsm` argument for `openssl` command line utility and `openssl_engine cloudhsm` option for nginx web server. They use `ENGINE_set_default(enginx, ENGINE_METHOD_ALL)` to change the default implementations of various cryptographic operations with ones provided by the engine.

I wonder if something like this would work:

```ruby
# Required only if using OpenSSL 1.0.2 or older to enable 'dynamic' engine.
# It adds support for loading "dynamic engines" with OpenSSL::Engine.by_id afterwards.
OpenSSL::Engine.load

e = OpenSSL::Engine.by_id("cloudhsm")
e.set_default(OpenSSL::Engine::METHOD_ALL)

fake_pkey = OpenSSL::PKey.read(File.read("path to pem file"))

# Use `fake_pkey` freely
```

**Comment by rhenium** [comment] 2020-02-21 09:35
On a side note, however, using OpenSSL::Engine#set_default has a huge effect as the cloudhsm engine will be used by every operation during the ruby process.

It is a missing feature of Ruby/OpenSSL to use engines selectively. For instance, using an engine just for a single signing operation is currently not possible (at least in a thread-safe manner). This is because we hard-code NULL in several locations, signaling OpenSSL to use the (currently) default engine.

https://github.com/ruby/openssl/blob/3ebae29c4a86376892d1fbc39313ca9a1c873c57/ext/openssl/ossl_pkey.c#L455

**Comment by rhenium** [comment] 2021-12-20 13:43
Closing this issue.

**Closed by rhenium** 2021-12-20 13:43 UTC

**Comment by thibaultponcelet** [comment] 2022-02-10 11:04
We would like to use cloudhsm only for some private keys at not for all of them in the same process, is the limitation mentioned by @rhenium still there?

**Comment by tim37021** [comment] 2022-03-31 10:59
I think this limitation is so serious. need to be reopen.
