### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by ioquatix** [ruby/openssl#257] opened 2019-06-13 06:18 UTC
@rhenium can we make 2.2.0 release soon?

**Comment by jdhollis** [comment] 2019-07-25 18:31
Any ETA on the next release?

**Comment by ioquatix** [comment] 2019-07-27 23:08
Hopefully soon.

**Comment by nikitarub** [comment] 2019-09-18 14:35
Having problems with https://github.com/ruby/openssl/pull/259
Waiting for release. 
What's the next release date?

**Comment by jdhollis** [comment] 2019-10-10 19:44
\*bump\*

**Comment by ioquatix** [comment] 2019-10-13 04:18
Because we've accepted a large number of PRs, I need to do a full code review before doing the next release, which will be a minor version bump. In addition, I'm not completely clear how we manage releasing this code independently of MRI, I need to investigate further.

@mame is there some process? Can we just release updated gem?

**Comment by bdewater** [comment] 2019-11-24 18:20
Bumping again is there's a month left before the next Ruby version is released.

@ioquatix I believe that is the process as documented here: https://github.com/ruby/openssl/blob/51181247a238b1fb148dad15b6fd2fa1471fc06e/CONTRIBUTING.md#relation-with-ruby-source-tree

**Comment by ioquatix** [comment] 2019-11-25 01:55
I have kicked this process off internally a week ago but the wheels are slow... will post an update once I know more. Thanks for the link @bdewater

**Comment by ioquatix** [comment] 2019-11-25 01:59
@rhenium I am going to meet @hsbt this week at Asakusa.rb - it would be great to do a release that day. Do you have time to meet up?

**Comment by hsbt** [comment] 2019-11-27 01:26
I start to migrate this repository into ruby-core at https://github.com/ruby/ruby/pull/2693

At least, We should resolve the test failure on ruby-core repository.

**Comment by davispuh** [comment] 2019-12-28 18:07
When new release could happen? There's several PRs merged in `master` which haven't been released. And last `v2.1.2` release is a year old.

![attels](https://user-images.githubusercontent.com/651800/71547813-8ecb7180-29ad-11ea-9a9f-7208ead06d9d.png)

**Comment by ioquatix** [comment] 2019-12-28 21:06
What was released in 2.7.0?

**Comment by jdhollis** [comment] 2019-12-28 21:15
Judging by the release notes, nothing new as far as the openssl gem: https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/

**Comment by ioquatix** [comment] 2019-12-28 22:17
@hsbt can you explain the status of the current release?

**Comment by hsbt** [comment] 2019-12-28 22:27
There is no progress. 

So, Originally https://github.com/ruby/ruby/pull/2693 is your work, not me.

**Comment by ioquatix** [comment] 2019-12-28 22:31
@hsbt thanks, I will sort it out.

**Comment by ioquatix** [comment] 2019-12-28 22:37
Okay, so most/all of the changes in the Ruby source code have been down streamed now.

In order to get to a 2.2.0 release, we need to address all the outstanding issues here: https://github.com/ruby/openssl/milestone/1

If you have time to help with this, please jump into an issue.

**Comment by hsbt** [comment] 2019-12-29 00:08
@ioquatix 

The current master branch was broken with the Windows platform. You should fix it before releasing 2.2.0.

see https://github.com/ruby/ruby/runs/322277594#step:10:1431

**Comment by ioquatix** [comment] 2019-12-29 04:04
Thanks I will check

**Comment by bdewater** [comment] 2019-12-31 18:33
> In order to get to a 2.2.0 release, we need to address all the outstanding issues here: https://github.com/ruby/openssl/milestone/1

IIRC before the Ruby 2.7 release window was missed that list was a lot smaller. Is there a reason to push back the next release even further once the Windows build is fixed? To me it seems having a release as soon as possible and syncing with Ruby trunk would be preferable over more/continued drift.

**Comment by jdhollis** [comment] 2020-01-27 19:25
This release has been lingering for quite a while. I don't know what the typical process is, but is there something I can do to help ship this?

**Comment by ioquatix** [comment] 2020-01-27 21:16
https://github.com/ruby/openssl/milestone/1

**Comment by jdhollis** [comment] 2020-01-27 21:46
Ok. So if I understand you correctly, we just need to close the issues referenced in that milestone.

Is there a way forward where we vet and ship the changes already committed to master in a point release?

**Comment by ioquatix** [comment] 2020-01-27 22:54
There is so much stuff that has not been released for so long, so it will require a bit of effort but yeah it’s very close.

**Comment by jdhollis** [comment] 2020-01-27 23:15
What is the process for preparing a release?

**Comment by hsbt** [comment] 2020-01-28 05:42
Again, At least, we need to fix https://github.com/ruby/ruby/pull/2693 with the master of ruby/openssl.

**Comment by rhenium** [comment] 2020-05-10 06:18
A blocker is OpenSSL::SSL::SSLContext#add_certificate_chain_file. It has a pending change and I don't want to include it in an incomplete state.

The initial implementation in commit 46e4bdba40c5e9c0b84b9ce8a3d1a2012bb1136e was not really useful. The issue is described in https://github.com/ruby/openssl/issues/305. https://github.com/ruby/openssl/pull/309 extended it to take the corresponding private key together. However, the new implementation was incompatible on Windows and was reverted by https://github.com/ruby/openssl/pull/320.

(The prerequisite to implement it in) an alternative way is https://github.com/ruby/openssl/issues/288, and it's still cooking.

**Comment by jdhollis** [comment] 2020-05-10 19:45
I still think it's worth putting out a point release to get the other changes out.

I've got client waiting on a change I committed last summer—it’s a blocker to the release of two open source libraries.

**Comment by ioquatix** [comment] 2020-05-10 23:45
> A blocker is OpenSSL::SSL::SSLContext#add_certificate_chain_file

We can push that to the 2.3 release.

**Closed** 2020-05-13 06:42 UTC

**Comment by rhenium** [comment] 2020-05-13 06:46
v2.2.0 is now pushed to rubygems.org.
